name: PUBLISH_NEXUS-REPOSITORY

on:
  push:
    tags:
      - 'v*.*.*'  # v Semantic Version Tag (ex: v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create gradle.properties from secret
        run: |
          echo "${{ secrets.GRADLE_PROPERTIES }}" > gradle.properties
          chmod 600 gradle.properties  # 보안 강화를 위해 파일 권한 설정

      - name: Show created file (debug)
        run: cat gradle.properties | grep -v password

      - name: Publish to Nexus
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}    # 태그명 추출
          VERSION=${TAG_NAME#v}                # 접두사 제거
                    if [[ ! $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Invalid version format. Expected x.y.z, got $VERSION"
            exit 1
          fi
          echo "Publishing version $VERSION"   # 버전 확인
          ./gradlew publish -Pversion=$VERSION --parallel --build-cache # Nexus 배포